"""Planner Agent - creates personalized study plans."""

from google.adk.agents.llm_agent import Agent

import app.database.session as db_session
from app.agents.utils import generate_content, retrieve_context
from app.config import settings
from app.database.crud import save_study_plan, track_progress


def create_study_plan(document_id: int, goals: str = "") -> dict:
    """Create a personalized study plan for a document.

    Args:
        document_id: ID of the document to study.
        goals: Optional learning goals from the student.

    Returns:
        Dictionary with the study plan and status.
    """
    context = retrieve_context("main topics concepts key ideas summary", document_id=document_id)
    if not context:
        return {"status": "error", "message": "No content found for this document"}

    prompt = f"""Based on the following study material, create a detailed study plan.

STUDY MATERIAL:
{context[:8000]}

STUDENT GOALS: {goals or "General mastery of the material"}

Create a structured study plan with:
1. Overview of key topics
2. Recommended study order (with time estimates)
3. Learning objectives for each section
4. Suggested review schedule
5. Practice recommendations

Format the plan in clear markdown."""

    plan_content = generate_content(
        prompt,
        system_instruction="You are an expert educational planner. Create practical, actionable study plans.",
        temperature=0.5,
    )

    db = db_session.SessionLocal()
    try:
        plan = save_study_plan(db, document_id=document_id, plan_content=plan_content)
        track_progress(
            db,
            document_id=document_id,
            activity_type="study_plan_created",
            details="Study plan generated by Planner Agent",
        )
        return {
            "status": "success",
            "plan_id": plan.id,
            "plan_content": plan_content,
            "message": "Study plan created successfully",
        }
    except Exception as e:
        return {"status": "error", "message": str(e)}
    finally:
        db.close()


planner_agent = Agent(
    model=settings.model_name,
    name="planner_agent",
    description="Creates personalized study plans from uploaded documents.",
    instruction="""You are the Planner Agent for StudyMate AI.
Your role is to analyze uploaded study materials and create personalized study plans.
Use the create_study_plan tool to generate structured study plans with topics,
time estimates, learning objectives, and review schedules.
Always consider the student's goals when creating plans.""",
    tools=[create_study_plan],
)

root_agent = planner_agent
